In [22]:
# coding=utf-8

# 读取图片


import cv2      # 导入opencv包


img_1 = cv2.imread('picture/one.jpg',cv2.IMREAD_COLOR)
img_2 = cv2.imread('picture/one.jpg', cv2.IMREAD_GRAYSCALE)
"""
imread()读取图片，第一个参数表示图片的路径，第二个参数表示读取图片的形式(彩图/灰度图像)
cv2.IMREAD_COLOR:彩色
cv2.IMREAD_GRAYSCALE:灰度图像
没有第二个参数则默认读取彩图
"""
print("彩色:\n" , img_1)
print("黑白:\n" , img_2)


彩色:
 [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
黑白:
 [[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


In [23]:
import cv2


# 使用窗口展示图片

img = cv2.imread('picture/one.jpg')
cv2.imshow('img', img)
"""
imshow()使用窗口显示图片，参数1是窗口的名字，是一个字符串;参数2是图片变量
"""
print('打开成功')
cv2.waitKey(0)
"""
等待时间，毫秒级，0代表任意键终止
"""
cv2.destroyAllWindows()
"""
关闭所有窗口
"""

打开成功


'\n关闭所有窗口\n'

In [24]:
# 上面的几段代码可以写为一个函数,方便随时调用，提高代码复用性

def cv_show(name, img):
    cv2.imread(name, img)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [25]:
import cv2


# 查看图片属性

img = cv2.imread('picture/one.jpg')
print(img.shape)
"""
img.shape会得到三个图片的属性值：依次为高度height，宽度weight，颜色通道数(彩色图像有BGR三个通道，而灰度图只有亮度一个通道)
需要注意的是在opencv中颜色是BGR而不是常见的RGB
"""

(272, 202, 3)


'\nimg.shape会得到三个图片的属性值：依次为高度height，宽度weight，颜色通道数(彩色图像有BGR三个通道，而灰度图只有亮度一个通道)\n需要注意的是在opencv中颜色是BGR而不是常见的RGB\n'

In [27]:
import cv2


# 保存图片

img = cv2.imread('picture/one.jpg',cv2.IMREAD_GRAYSCALE)
cv2.imwrite('picture/one_GRAYSCALE.jpg', img)

"""
imwrite()函数用来保存图片，参数1表示图片保存的绝对路径(文件夹/完整文件名),参数2表示保存的图片
"""
print(cv2.imwrite('picture/one_GRAYSCALE.jpg', img))
# 此处我们可以看到如果保存成功的话会返回一个true

True


In [29]:
print(type(img))
# 使用type函数来查看img的属性：NumPy 最重要的一个特点是其 N 维数组对象 ndarray

<class 'numpy.ndarray'>


In [30]:
print(img.size)
# 使用.size来计算该图片的像素值

54944


In [31]:
print(img.dtype)
# 查看该变量的数据类型

uint8
